---
- hosts: prod-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me1 vijayalakshmipushpendra/insure-me:1.0
